<?php

namespace Magenest\Rules\Model\ResourceModel\Rule;

use Magenest\Rules\Model\Rule;

/**
 * Class Collection
 * @package Magenest\Rules\Model\ResourceModel\Rule
 */
class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{


    protected function _construct()
    {
        $this->_init(Rule::class, \Magenest\Rules\Model\ResourceModel\Rule::class);
    }

    /**
     * @return \Magento\Framework\DataObject[]
     */
    public function getItems()
    {
        $this->addFieldToSelect('*')->addFieldToFilter('status', ['eq' => 'pending']);
        return parent::getItems(); // TODO: Change the autogenerated stub
    }

}
